services:
  # Backing services.
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql

  redis:
    logging:
      driver: none
    image: redis
    restart: always
    command: "redis-server --port ${REDIS_PORT}"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ${REDIS_DATA_PATH}:/data

  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
    # TODO: change default port through envs? Couldnt find it.
      - "5672:${RABBITMQ_PORT}"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

  # Services.
  
