CREATE TABLE IF NOT EXISTS casino_game_config (
  id INT AUTO_INCREMENT PRIMARY KEY,
  game_type VARCHAR(32) NOT NULL,
  min_bet INT NOT NULL DEFAULT 10,
  max_bet INT NOT NULL DEFAULT 100000,
  house_edge DECIMAL(5,4) NOT NULL DEFAULT 0.0250,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  config_json JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
