ALTER TABLE scores        ADD COLUMN watched_count INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE scores_relax  ADD COLUMN watched_count INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE scores_ap     ADD COLUMN watched_count INT UNSIGNED NOT NULL DEFAULT 0;
