[mysqld]
# Perf
innodb_buffer_pool_size = 4G
innodb_flush_log_at_trx_commit = 1
innodb_log_file_size = 256M
innodb_flush_method = O_DIRECT
table_open_cache = 1024
max_allowed_packet = 16M
slow_query_log = ON
long_query_time = 2
wait_timeout = 31536000
interactive_timeout = 31536000