name: production-deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Set up WireGuard
        uses: egor-tensin/setup-wireguard@v1
        with:
          endpoint: '${{ secrets.WIREGUARD_ENDPOINT }}'
          endpoint_public_key: '${{ secrets.WIREGUARD_PUBLIC_KEY }}'
          ips: '${{ secrets.WIREGUARD_ADDRESS }}'
          allowed_ips: '${{ secrets.WIREGUARD_ALLOWED_IPS }}'
          private_key: '${{ secrets.WIREGUARD_PRIVATE_KEY }}'
          preshared_key: '${{ secrets.WIREGUARD_PRESHARED_KEY }}'

      - name: Deploy new version on production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.NEW_SSH_HOST }}
          username: ${{ secrets.NEW_SSH_USERNAME }}
          key: ${{ secrets.NEW_SSH_KEY }}
          port: ${{ secrets.NEW_SSH_PORT }}
          script_stop: true
          script: |
            cd /home/realistikosu/workbench
            git fetch origin
            git checkout origin/${{ steps.extract_branch.outputs.branch }}
            git pull origin ${{ steps.extract_branch.outputs.branch }}
            
            make build
            make restart
            
